### ISSUE TITLE
List 中没有getFirst方法

### ISSUE THREAD

**Issue by hanchao0606** [WongSilver/spring-cloud-study#2]
我用的java17没有getFirst这个方法呢
![1723714295696](https://github.com/user-attachments/assets/a8281a77-70bd-494b-a2c9-4b0dc4c57076)

**Comment by WongSilver** [comment]
我试了jdk21有的
![image](https://github.com/user-attachments/assets/ff2c0c80-08e5-4479-8c74-b20e7365611a)

三种方案. 
1.你改成jdk21
2. 用stream取第一个(默认值0)
3.你把上面的转成LinkedList

以上方案都是取集合第一个的办法, 都没测试过 你可以试试

**Comment by hanchao0606** [comment]
你这个项目是用jdk21吗？

**Comment by WongSilver** [comment]
> 你这个项目是用jdk21吗？

是的,我用的jdk21😂

**Comment by hanchao0606** [comment]
那我也换成21吧

**Comment by WongSilver** [comment]
> 那我也换成21吧

好的，那我关闭issue了
